[project]
name = "asgard"
version = "0.1.0"
description = "asgard: home of my science"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "loki",
  "bifrost",
  "vegtamr",
]

[tool.uv.sources]
loki = { path = "sindri/loki" }
bifrost = { path = "sindri/bifrost" }
vegtamr = { path = "sindri/vegtamr" }
